repos:
  - repo: local
    hooks:
      - id: lint-check
        name: Run ruff linter
        entry: just lint
        language: system
        stages: [pre-commit]
        verbose: true
        pass_filenames: false
      - id: type-check
        name: Run mypy type checker
        entry: just type-check
        language: system
        stages: [pre-commit]
        verbose: true
        pass_filenames: false
      - id: unit-tests
        name: Run unit tests
        entry: just test
        language: system
        stages: [pre-commit]
        verbose: true
        pass_filenames: false
